name: Check Spelling

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  spelling:
    runs-on: ubuntu-latest

    # prevent duplicate runs when a PR exists
    if: github.event_name != 'push' || github.event.pull_request == null

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run spelling check
        uses: check-spelling/check-spelling@main
        with:
          checkout: true
          check_file_names: 1
          only_check_changed_files: 1
          spell_check_this: check-spelling/spell-check-this@main
          use_magic_file: 1
          # comment on PR, not commits
          post_comment: ${{ github.event_name == 'pull_request' && '1' || '0' }}
          warnings: bad-regex,binary-file,deprecated-feature,large-file,limited-references,no-newline-at-eof,noisy-file,non-alpha-in-dictionary,token-is-substring,unexpected-line-ending,whitespace-in-dictionary,minified-file,unsupported-configuration,no-files-to-check
          extra_dictionary_limit: 20
          extra_dictionaries:
            cspell:software-terms/dict/softwareTerms.txt
