name: vorago-basic
on:
    schedule:
       - cron: '0 0 * * WED'
    push:
      branches:
        - master
      paths:
        - 'basic-guides/vorago-basic/*_combined.txt'
jobs:
  update-vorago-basic:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: ./basic-guides/vorago-basic/update.sh
